server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: https://customer-service-i7ps.onrender.com
          predicates:
            - Path=/api/v1/customers/**

        - id: order-service
          uri: https://order-service-t6cp.onrender.com
          predicates:
            - Path=/api/v1/orders/**
