server:
  port: 8084

spring:
  application:
    name: customer-service

  cloud:
    config:
      enabled: false   # âœ… STEP-6 FIX (Config Server disable)

  data:
    mongodb:
      uri: mongodb+srv://maheshbhai:Mahesh123Mongo@cluster1.ju5rpoa.mongodb.net/customerdb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
    fetch-registry: true
