server:
  port: 8081

spring:
  application:
    name: customer-service

  data:
    mongodb:
      uri: mongodb+srv://maheshbhai:Mahesh123Mongo@cluster1.ju5rpoa.mongodb.net/customerdb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-196g.onrender.com/eureka
    register-with-eureka: true
    fetch-registry: true
