server:
  port: 8081

spring:
  application:
    name: customer-service

  cloud:
    config:
      enabled: false   # ðŸ‘ˆ THIS IS THE KEY FIX

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-196g.onrender.com/eureka
    register-with-eureka: true
    fetch-registry: true
