server:
  port: 8081   # internal only

spring:
  application:
    name: customer-service

  config:
    enabled: false   # Render pe config server disable

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-196g.onrender.com/eureka
    register-with-eureka: true
    fetch-registry: true
